### ISSUE TITLE
Representation of WT hotels on a map

### ISSUE THREAD

**Issue by AugustoL** [windingtree/wt-hackathon#34]
Show one or more hotels on a map.

- Browser extension which adds hotels on top of an existing maps.
- Augmented reality

To work on this you we recommend you to use [wt-read-api](https://github.com/windingtree/wt-read-api)

**Comment by kvakes** [comment]
Like Google Maps? Why browser extension then?

**Comment by JirkaChadima** [comment]
It could grab data from WT platform and display it as an overlay on an existing mapping solution - as an addition to existing, registered properties on such map platform. Or maybe it could somehow hijack a card with a registered property and add a direct booking link through Winding Tree? That's why a browser extension.
